name: Release & Remove obsolete

on:
  push:
    branches: [master]

jobs:
  build:
    name: Deploy server to Heroku
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_TOKEN}}
          heroku_app_name: backend-travel
          heroku_email: ${{secrets.EMAIL}}
          usedocker: true
          appdir: server
          healthcheck: https://backend-travel.herokuapp.com/